### ISSUE TITLE
Version of flask-login is not pinned and update has broken CSP

### ISSUE THREAD

**Issue by rossjones** [ckan/ckan-service-provider#27]
Flask-login is unpinned in setup.py, and whilst it was on 0.2.11 it was fine.  It's now been upgrade to 0.3.0 and a method (current_user.is_authenticated()) is now a property.

Options for fixes:

1. Pin flask-login to 0.2.11
2. Pin to 0.3.0 and change is_authenticated() to is_authenticated.

**Comment by amercader** [comment]
Merged, bumped version to 0.0.4 and upgraded DataPusher requirement.

cheers for investigating and the quick fix @rossjones

**Comment by filipefigcorreia** [comment]
I've just stumbled on this very issue. I was using the branch labeled as "stable", but that one is anterior to 0.0.4.

**Comment by amercader** [comment]
Sorry, the `stable` branches have now been updated. We should probably just use master, I'll update the docs to reflect this.
