### ISSUE TITLE
Release Needed to Fix SQLAlchemy Incompatibility

### ISSUE THREAD

**Issue by JackMc** [ckan/ckan-service-provider#31]
As fixed in #30, it is causing us a lot of trouble that the version of ckan-service-provider on PyPi requires a specific version of SQLAlchemy (see issue https://github.com/datacats/ckan-multisite/issues/37, https://github.com/datacats/datacats/issues/334). 

If a release of ckan-service-provider were released on PyPi, this would allow our automated tooling to pull down the correct version of SQLAlchemy without weird hackery such as installing the correct version of SQLAlchemy manually or grabbing ckan-service-provider from Git.

**Comment by amercader** [comment]
@JackMc Sorry, I don't understand. ckanserviceprovider 0.0.5, which is on PyPI includes the fix on #30. What is the problem exactly?

**Comment by JackMc** [comment]
Whoops, my apologies! Must be something on our end, then.

**Comment by SAEnergyData** [comment]
Experienced the same problem. The issue lies with datapusher's stable branch still using 0.0.4 ...

**Comment by amercader** [comment]
@SAEnergyData sorry about that, I've updated the `stable` branch. I'd recommend using the latest release or master instead of that one. I've updated the docs to reflect this.

**Comment by SAEnergyData** [comment]
Thanks a lot.
