### ISSUE TITLE
Needs a release before CKAN 2.7 comes out

### ISSUE THREAD

**Issue by davidread** [ckan/ckan-service-provider#35]
This is because Datapusher is currently broken with CKAN master (soon to be released as 2.7): https://github.com/ckan/datapusher/issues/124

So please can someone with permission @amercader do a release of ckan-service-provider (with the fix https://github.com/ckan/ckan-service-provider/pull/32 ) and then I'll repoint Datapusher at pointed at that new released version.

**Comment by amercader** [comment]
@davidread Done https://pypi.python.org/pypi/ckanserviceprovider/0.0.6

**Comment by amercader** [comment]
Also added to pypi for this and datapusher in case it helps

**Comment by davidread** [comment]
Super, thanks!
