### ISSUE TITLE
dependencies broken because of no version pinning

### ISSUE THREAD

**Issue by gerbyzation** [ckan/ckan-service-provider#38]
the flask-login requirement is unpinned in `setup.py`, and from 0.4.0 onward the import has changed from ` flask.ext.login` to `flask_login`, causing an exception.

**Comment by gerbyzation** [comment]
Ok, it actually seems to be that flask has received it first major release which is the cause of this. Nontheless, the source of the issue remains the same.

**Comment by s-chand** [comment]
I just had this issue as well

**Comment by s-chand** [comment]
@amercader any chance that this can be looked into anytime soon?
@gerbyzation has created a fix with [#39](https://github.com/ckan/ckan-service-provider/pull/39)
