### ISSUE TITLE
BUG: APScheduler version needs to be no greater than 3.9.1.post1

### ISSUE THREAD

**Issue by jqnatividad** [ckan/ckan-service-provider#59]
If ckanserviceprovider is installed from pypi, it does not work properly as it pulls in v3.10 (released Jan 31, 2023), which causes it to not process jobs properly:

https://github.com/ckan/ckan-service-provider/blob/4dfeb0fd8c6e96698bdb7ee9893d292dbf509121/setup.py#L13-L19

Even if ckanserviceprovider is installed from source it also doesn't work as the `requirements.txt` file specifies APScheduler 3.9.1, which was [yanked](https://pypi.org/project/APScheduler/#history):

https://github.com/ckan/ckan-service-provider/blob/4dfeb0fd8c6e96698bdb7ee9893d292dbf509121/requirements.txt#L1-L6

# Proposed solution:
* set `APScheduler>=2.1.2,<3.10.0` in setup.py
* set `APScheduler==3.9.1.post1` in requirements.txt

**Comment by markstuart** [comment]
I just hit this one as well, wish I'd checked the issues on here a bit better so it didn't take me so long to find the issue :man_facepalming: 

I'm currently explicitly installing 3.9.1.post1 in my datapusher dockerfile to prevent it building with 3.10.0

**Comment by amercader** [comment]
@jqnatividad  @markstuart This makes sense and I've merged the PR but before doing a proper release I'd like to have the failing tests fixed. I had a quick look and they just need to be modernized and refactored to use `responses` instead of `httpretty`, but I don't have time to do it right now. If some of you wants to give it a go then great, if not it will have to wait.

**Comment by jqnatividad** [comment]
@markstuart , I know the feeling...

For us, it bit us in a HARD way - we were deploying to UAT with a customer and I was perplexed why Datapusher+ won't work and we were troubleshooting with the customer online for almost 3 hours.

So yeah, I'll take on fixing the test @amercader as we need to show the customer's DevOps team that the tests work before the next release next month.

Ultimately, I'm targeting to remove Datapusher+'s ckanserviceprovider dependency (https://github.com/dathere/datapusher-plus/issues/66), but I don't think I'll have it done before then.

**Comment by amercader** [comment]
@jqnatividad @markstuart I've released new versions for ckanserviceprovider (1.1.0) and Datapusher (0.0.20) with this fix included. We'll sort out the tests later
